name: searchx

services:
  redis:
    container_name: searchx-redis
    image: redis
    ports:
      - '6379:6379'

  mongo:
    container_name: searchx-mongo
    image: mongo
    ports:
      - '27017:27017'

  elasticsearch:
    container_name: searchx-elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
        - discovery.type=single-node
    image: elasticsearch:7.17.18