FROM node:8.17-alpine

RUN apk --no-cache add curl

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

EXPOSE 80

CMD [ "node", "scripts/server.js" ]
