name: Docker Image CI 
on: 
    push:
     branches:
        - 'master'

jobs: 
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and publish
              run: |
                echo "Building Docker Images"
                docker build  -t ghcr.io/levdops/worker:latest  -f ./Dockerfile.worker . 
                docker build  -t ghcr.io/levdops/server:latest  -f ./Dockerfile.server . 
                echo "Publishing Docker Images"
                docker push ghcr.io/levdops/worker:latest
                docker push ghcr.io/levdops/server:latest