name: Docker Image CI 
on: 
    push:
     branches:
        - 'master'
    workflow_dispatch:

permissions: write-all

jobs: 
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0
              with:
                mongodb-port: 27017
                mongodb-db: searchx-test
            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: 12
            - run: cp .env.example .env
            - run: npm ci
            - run: npm run start & npm test
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and publish
              run: |
                echo "Building Docker Images"
                docker build  -t ghcr.io/levdops/worker:latest  -f ./Dockerfile.worker . 
                docker build  -t ghcr.io/levdops/server:latest  -f ./Dockerfile.server . 
                echo "Publishing Docker Images"
                docker push ghcr.io/levdops/worker:latest
                docker push ghcr.io/levdops/server:latest